project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!exams/"
    - "!lab/"
    - "!hw/"
    - "!hw-solutions/"
    - "!lab-solutions/"
    - "!quiz/"
    - "!quiz-solutions"
    - "!in_class/"

website:
  title: "STAT 141"
  image: assets/math141-hex.png
  site-url: "XXX SITE URL HERE XXX"
  favicon: assets/favicon.ico
  navbar:
    title: false
    background: white
    foreground: "gray-800"
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: office_hours.qmd
        text: Office Hours
      # - href: inference_cheatsheet.qmd
      #   text: Inference Summary Tables
    tools:
      - icon: chat-dots-fill
        href: https://math141sp26.slack.com
        aria-label: Slack
      - icon: r-circle-fill
        href: https://rstudio.reed.edu/
        aria-label: RStudio Server
      - icon: bar-chart-fill
        href: https://www.gradescope.com/courses/1225246
        aria-label: Gradescope
      - icon: door-closed-fill
        href: https://moodle.reed.edu/course/view.php?id=6317
        aria-label: Moodle

format:
  html:
    theme:
      - sandstone
      - assets/styles.scss
    toc: true


resources: 
  - CNAME

editor: visual

