---
title: "Homework 5.5: Practice-Based Study Guide"
subtitle: "STAT 141, Week 6"
format: pdf
execute:
  echo: true
  warning: false
  message: false
---

## Due: Thursday, October 15th at 9:00am on Gradescope as a **PDF**

### Metacognitive Activities and Creating a Practice-Based Study Guide

A [2021 article from the Stanford Center for Teaching and Learning](https://teachingcommons.stanford.edu/news/promoting-student-metacognition) defines **Metacognition** as *"the awareness and ability of learners to assess their learning and develop learning strategies in accordance with their goals."*

The main idea is that the better that we're able to evaluate and understand our own learning, the more efficient we'll be at closing gaps between what we've actually learned and what we want to learn. Metacognitive activities can therefore help us deepen understanding of course material, and are a great way to study for exams. 

Yes, it is very, very early to be thinking about our final exam! No need to stress about it yet. But because the exam is so far off, and because we have already covered quite a lot of material, I want you to take this time to reflect on what you've learned so far and how you might like to deepen your understanding. This mini homework assignment will ask you to start creating a practice-based study guide for yourself that you can continue building on up until the final exam. 

Creating a study guide of any kind is an example of a metacognitive activity and is an excellent way to prepare for an exam. This kind of activity is usually much more effective than entirely rereading lecture material or the textbooks. You might be more familiar with study guides that summarize course content in a written, list-like format. Here, we'll focus on a type of study guide that centers practice problems and reflections about them.

You will still submit this assignment to Gradescope, and it will only be assessed for completion (*as in: you wrote at least a sentence for each question, but it doesn't need to be paragraphs*). The more effort you put into study guide creation, the more you'll be helping your future self when they sit down to study for the exam in December!

\newpage

### Exercise 1: Identify a gap

What has been a concept or task from the course so far that you feel least confident about? It may be helpful to review the quizzes and course schedule up until now. Try to focus on a concept or task that is somewhat specific (ex. "interpreting categorical variables in linear models" vs just "linear models", or "using Bayes rule" vs just "probability").

******************************************************************************



******************************************************************************



### Exercise 2: Practice

**a.** Find a practice problem related to your answer for Exercise 1. I recommend you source the problem from the slides, past assignments, or quizzes, and choose an example where you can deduce the solution either in the slides or from feedback on Gradescope. Note which problem it is here, and attempt to complete it (either here or on scratch paper) without looking at any solutions or grader feedback. *If you get stuck: that's okay! Write down what you tried or are thinking, and move on to the next part.*

******************************************************************************



******************************************************************************



**b.** Don't look at solutions yet. Write down any questions or confusions you have from your attempt at completing the problem. 

******************************************************************************



******************************************************************************



### Exercise 3: Self-assessment


**a.** Check your work against solutions, or discuss them with a course assistant, or ask a classmate if they can walk through the problem with you (or wait to discuss with Megan when she's back on 10/14). How did the practice problem go? Did you find a place where you went wrong?

******************************************************************************



******************************************************************************



**b.** If applicable, write down any unresolved questions or confusions after viewing or discussing the correct solutions to the problem. These can be followed up on by further investigating the slides, or discussing the problem further in office hours with course assistants or Megan. If you feel confident about your work, great! Leave yourself a note about any key idea or any mistakes to avoid that you want your December self to remember.

******************************************************************************



******************************************************************************


### Closing note

When studying for the final exam in December, I highly recommend you come back to this assignment and reuse these questions for more topics. We'll be happy to work through this process with you in office hours at any time.


