---
title: "Homework 8: Hypothesis Testing"
subtitle: "Math 141, Week 9"
author: "Your name here"
format: pdf
execute:
  echo: true
  warning: false
  message: false
---

In this homework assignment you will:

- Demonstrate proficiency with the concepts: null and alternative hypothesis, p-value, type I and II errors, power, and how these relate to specific research questions
- Consider some pitfalls associated with p-values


### Add any collaborators here!

I collaborated with...

**Remember that you are not allowed to use any internet resources or generative AI models (like ChatGPT or Claude) on your assignment. While there are many ways to achieve tasks in R, you may only use packages and functions that have been covered in this class. If you are unsure of how to approach an exercise or of what function to use, help is available to you! Please visit office hours, collaborate with your peers, or post in the Slack channel.**


# Exercises

## Exercise 1: Hypothesis Testing Setup

For each of the situations described in parts (a) - (c), do the following:

  (i) Describe the null and alternative hypotheses (in words)
  (ii) Describe the effects of a Type I and Type II error in context
  (iii) Indicate whether it makes more sense to use a larger significance level (such as $\alpha = 0.10$) or a smaller significance level (such as $\alpha = 0.01$), and briefly explain your reasoning.


**a.** A new drug with potentially dangerous side effects is tested to see if it is better than the drug currently in use. If it is found to be effective, it will be prescribed to millions of people.

*********************************************************************************




*********************************************************************************


**b.** Two slightly different versions of a statistics exercise are given to a 10am and 12pm section of Math 141 and the proportions of students in each class who get the question correct are recorded. We wish to determine whether one question was more difficult than the other.

*********************************************************************************




*********************************************************************************


**c.** You test whether taking a vitamin supplement reduces the duration of symptoms of the common cold. There are no (known) harmful side effects of the supplement.

*********************************************************************************




*********************************************************************************


## Exercise 2: Interpreting Results and Misconceptions

After graduating, you decide to apply for positions as a statistical consultant. A friend who graduated a few years prior and already works in the field has sent you the following set of scenarios. If she is impressed by your responses, she will recommend your name to a hiring team. For each response, be sure to fully explain your reasoning.


**a.** Melatonin pills are a popular remedy for providing insomnia relief. A company developed a new formulation of melatonin pill and conducted a randomized controlled trial on a random sample of 2,000 American adults who were already experiencing insomnia and using melatonin pills. A 95% confidence interval for mean increase in sleep hours per typical night was calculated based on data from the trial: (0.09, 0.13) hours. A hypothesis test for the null hypothesis of no effect resulted in $p$-value 0.0001. **Assess whether the evidence suggests the new formulation is a substantial improvement over melatonin pills currently available on the market. Limit your response to no more than five sentences.**

*********************************************************************************




*********************************************************************************



**b.**  The company would like to announce in a press release that based on these data there is only a 0.01% chance that their new melatonin pill is not actually effective, or in other words, that there is a 99.99% chance that their new formulation on average improves the amount of sleep in American adults with insomnia. **Explain why this statement is misleading.**

*********************************************************************************




*********************************************************************************



**c.**  Suppose that a researcher in environmental science is working on an analysis using data collected at 200 locations across the United States during January of 2024 and January of 2014. The researcher proposes the following approach: for each location, conduct a two-sided hypothesis test at the $\alpha = 0.05$ significance level to compare the mean temperature in January 2024 to the mean temperature in January 2014. He plans to conclude there is evidence of temperature warming for the locations at which mean temperature in January 2024 is significantly higher than mean temperature in January 2014, and specifically present only those significant results to his principal investigator. **Identify at least one aspect of this analysis plan that is problematic; explain your reasoning as to why there is an issue.**

*********************************************************************************




*********************************************************************************


**d.**  A recent study of $n = 20$ dogs investigated the effects of classical music on dog separation anxiety (measured on a 0-10 point scale) and found inconclusive results. Researchers were unable to reject the null hypothesis of zero effect. Researchers report that classical music reduced anxiety in the sample by an effect size of -2.5, and provide a 95% confidence interval of [-6.5, 1.5] and a p-value of $p = 0.34$ for $\alpha = 0.05$. **What are 2 distinct reasons why the study failed to reject the null hypothesis, and how could researchers adjust a future study to distinguish between these 2 cases?** You can assume that the study was perfectly implemented - failure to reject the null was not due to any sampling or implementation error or accident.

*********************************************************************************




*********************************************************************************


## Exercise 3: Mayor Election Hypothesis Testing

Imagine you're a political pollster interested in inferring the **proportion of voters who support Carmen Rubio for Portland mayor** back in the November 2024 election. You conduct a survey of 200 likely voters and find that 88 of them support Ms. Rubio.

**a.** In labs 7 and 8, you practiced working with code we saw in lecture to construct confidence intervals and perform hypothesis testing using simulation-based methods. This exercise will ask you to adapt and apply these methods to a new setting. Review examples from lecture and/or lab, and in your own words, list general steps for constructing confidence intervals **and** for performing hypothesis testing using simulation-based methods.




**b.** Using the survey results below and simulation-based methods, create a **90%** confidence interval for $p$, the overall proportion of likely Portland voters who support Carmen Rubio for mayor. [Only code]

*******************************************************************************

```{r}
sample_mayor <- data.frame(rubio = c(rep("Yes", 88),
                                     rep("No", 112)))

# Your work below. Don't forget to set your seed!



```

*******************************************************************************



**c.** Carefully interpret your confidence interval in context. What can you learn about Ms. Rubio's electoral chances from this confidence interval? [Only text]

*******************************************************************************




*******************************************************************************



**d.** Suppose we're also interested in knowing if it's plausible that Ms. Rubio will receive less than 50\% of the votes in the upcoming election for mayor. **To test this question, follow the hypothesis testing steps to calculate a simulation-based p-value** for the alternative hypothesis that $p<0.5$ vs. the null hypothesis that $p=0.50$ at the 0.05 level. [Only code]

*******************************************************************************




*******************************************************************************



**e.** Carefully interpret your p-value in context. What can you learn about Ms. Rubio's electoral chances from this hypothesis test? [Only text]

*******************************************************************************




*******************************************************************************



**f.** Consider your conclusions from 1(c) and 1(e). *In context*, what is different about your conclusions from the inferential procedures of confidence intervals and hypothesis tests? [Only text]

*******************************************************************************





*******************************************************************************



**g.** You should have found a right endpoint for your 90% confidence interval of about 0.50 in (a), and a p-value of around 0.05 in (c). In other words, we are right at the "border" of evidence that 50% of voters support Ms. Rubio for mayor. **In your own words, explain why these two inferential procedures "align" in this sense.** [Only text]

*******************************************************************************





*******************************************************************************




## Exercise 4: P-Value Pitfalls

The pitfalls of $p$-values have been discussed for decades, and in 2016 the *ASA Statement on p-Values and Statistical Significance* was developed primarily to discuss what not to do with $p$-values.


**a.**  To better understand the debate around the use of $p$-values, read the article "A Significant Problem" (written by Lydia Denworth) in the file `scientific_american_p_values.pdf`, available here with your assignment. (*No response required for part a.*)



**b.**  Describe one reason why it is not advisable to label all results with p-values $p < 0.05$ as "significant" and all results with p-values $p \geq 0.05$ as not significant.

*********************************************************************************




*********************************************************************************




**c.**  Take a look at the section "Statistical Significance" on pages 2-4, which is intended to explain some concepts underpinning statistical significance in language accessible to those who have not taken a statistics course. **Describe in 2-3 sentences something you thought was explained/illustrated particularly well in this section.**

*********************************************************************************




*********************************************************************************



**d.** Try doing some $p$-hacking of your own with ["Hack Your Way To Scientific Glory"](https://stats.andrewheiss.com/hack-your-way/) to reach a "publishable" result. **How did you get to the statistically "significant" result?**

*********************************************************************************




*********************************************************************************


**e.**  One proposed reform involves requiring study authors to publicly pre-register their statistical analysis plans prior to any data collection and to report when they deviate from them. **Explain in 2-4 sentences why this approach can help guard against $p$-hacking.**

*********************************************************************************




*********************************************************************************
